packages:
  - '.'
  - 'packages/*'
  - 'packages/website'
  - 'packages/studio'
  - 'packages/shared'
  - 'packages/firmware'
  - 'tools/*'

# Allow builds for specific native modules
allowBuilds:
  esbuild: true
