#pragma once
// ===============================================================
//  config_store.h - Configuration data structures
//
//  These structs mirror exactly the JSON that the SvelteKit app
//  sends. If you change the JSON, change these structs to mirror it.
// ===============================================================

#include <stdint.h>
#include <stdbool.h>
#include "esp_err.h"

// Structural limits: single source of truth in config-schema.ts,
// generated by `pnpm codegen` (CONFIG_MAX_PROFILES, CONFIG_MAX_LAYERS,
// CONFIG_NAME_MAX_LEN, CONFIG_NUM_KEYS, PROFILE_ICON_*).
#include "config_limits.gen.h"

#define CONFIG_MAX_COMBOS      16

// Macro step definitions
// MACRO_COUNT, MACRO_MAX_STEPS, MACRO_NAME_MAX_LEN come from config_limits.gen.h

typedef enum {
    MACRO_STEP_KEY_DOWN = 0,
    MACRO_STEP_KEY_UP   = 1,
    MACRO_STEP_DELAY_MS = 2,
} kb_macro_step_type_t;

typedef struct {
    kb_macro_step_type_t type;
    uint16_t             keycode_or_delay;  // HID keycode (KEY_DOWN/UP) or ms (DELAY, max 1000)
} kb_macro_step_t;

typedef struct {
    char            name[MACRO_NAME_MAX_LEN];  // Friendly name (empty -> "Macro N")
    uint8_t         step_count;
    kb_macro_step_t steps[MACRO_MAX_STEPS];
} kb_macro_t;

// Combo definition (mirrors keymap's internal type)
#define KEYMAP_COMBO_MAX_KEYS   4

typedef struct {
    uint8_t  keys[KEYMAP_COMBO_MAX_KEYS];
    uint8_t  key_count;
    uint16_t action;
    uint16_t window_ms;
    bool     active;
} kb_combo_t;

// -- A layer: array of keycodes --
typedef struct {
    char     name[CONFIG_NAME_MAX_LEN];    // Ex: "Base", "Fn", "Media"
    uint16_t keys[CONFIG_NUM_KEYS];        // Action for each key (KB_NUM_KEYS)
    uint16_t encoder_cw;                   // Encoder clockwise
    uint16_t encoder_ccw;                  // Encoder counter-clockwise
    uint16_t encoder_press;                // Encoder button
    uint8_t  encoder_sensitivity;          // 0 = inherit global, 1-4 = override
} kb_layer_t;

// -- A profile: several layers + combos + macros --
typedef struct {
    char        name[CONFIG_NAME_MAX_LEN]; // Ex: "Default", "Gaming", "Dev"
    uint8_t     icon[PROFILE_ICON_BYTES];  // Bitmap 24x24 1bpp (0 = no icon)
    uint8_t     layer_count;
    kb_layer_t  layers[CONFIG_MAX_LAYERS];
    uint8_t     combo_count;
    kb_combo_t  combos[CONFIG_MAX_COMBOS];
} kb_profile_t;

// -- Global orientation --
typedef enum {
    ORIENTATION_0   = 0,   // Normal
    ORIENTATION_90  = 1,   // +90 deg CW
    ORIENTATION_180 = 2,   // 180 deg
    ORIENTATION_270 = 3,   // +270 deg CW (= -90 deg)
} kb_orientation_t;

// -- Encoder config --
typedef struct {
    uint8_t sensitivity;   // Step per event: 1 (1 click/detent) to 4 (1 click/4 detents)
} kb_encoder_config_t;

// -- LED chain extension --
typedef enum {
    LED_EXT_MODE_OFF      = 0,   // Extension off
    LED_EXT_MODE_MIRROR   = 1,   // Copies the colors of the 10 keys in a loop
    LED_EXT_MODE_AMBIENT  = 2,   // Single soft color (breathe)
    LED_EXT_MODE_STATIC   = 3,   // Configurable static color
    LED_EXT_MODE_REACTIVE = 4,   // Flash on key pressed
    LED_EXT_MODE_HYPERION = 5,   // Driven by Hyperion NG bridge (set_extension_frame)
} kb_led_ext_mode_t;

typedef struct {
    bool              enabled;
    uint8_t           count;          // Number of extension LEDs (1-50)
    kb_led_ext_mode_t mode;
    uint8_t           r, g, b;       // Static color (if mode = STATIC or AMBIENT)
    uint8_t           brightness;    // 0-255 (independent of key brightness)
    uint16_t          max_power_mw;  // Max budget in mW (0 = unlimited, default: 500)
} kb_led_extension_t;

// -- BLE config --
typedef struct {
    char device_name[CONFIG_NAME_MAX_LEN];   // Name broadcast over BLE
    char slot_names[2][CONFIG_NAME_MAX_LEN]; // Ex: ["PC Bureau", "Home Assistant"]
    uint8_t active_slot;                     // 0 or 1
} kb_ble_config_t;

// -- OLED widgets --
// kb_widget_type_t is generated from WIDGET_TYPE (config-schema.ts):
#include "widget_types.gen.h"

#define WIDGET_MAX_CUSTOM_LEN  13   // 12 chars max + '\0'
#define DISPLAY_MAX_WIDGETS     8

// Logical 4x4 grid (span-based v1 model). Must stay in sync with
// WIDGET_GRID_* / WIDGET_CAPABILITIES in config-schema.ts (source of truth).
#define WIDGET_GRID_COLS    4
#define WIDGET_GRID_ROWS    4
#define WIDGET_MIN_BAND_PX  10   // fixed outer band (col/row 0 and 3)

// Flags in kb_widget_t.opts[0]
#define WIDGET_OPT_CLOCK_24H        (1u << 0)   // 24h clock (otherwise 12h)
#define WIDGET_OPT_CLOCK_SHOW_DATE  (1u << 1)   // 2x2 clock: show the date

typedef struct {
    kb_widget_type_t type;
    uint8_t          x;      // 0..WIDGET_GRID_COLS-1
    uint8_t          y;      // 0..WIDGET_GRID_ROWS-1
    uint8_t          w;      // span in cells
    uint8_t          h;
    uint8_t          opts[2];                      // flags per type (cf. WIDGET_OPT_*)
    char             custom_text[WIDGET_MAX_CUSTOM_LEN];
    uint8_t          icon[PROFILE_ICON_BYTES];     // bitmap 24x24 1bpp (ICON type only)
} kb_widget_t;

// -- Screen config --
typedef struct {
    uint8_t     brightness;       // 0-255
    uint16_t    timeout_s;        // Turn off after N seconds
    kb_widget_t widgets[DISPLAY_MAX_WIDGETS];
    uint8_t     widget_count;
    // Reference for the clock widget: unix timestamp + uptime at set_time
    uint32_t    clock_base_unix_ts;
    uint64_t    clock_base_uptime_ms;
} kb_display_config_t;

// -- Power config --
typedef struct {
    uint32_t sleep_timeout_s;       // Deep sleep after N seconds of inactivity
    uint8_t  battery_critical_pct;  // battery % -> blinking red LED
    // Battery presence (SpinPad variants without a LiPo battery):
    //   "auto" -> ADC auto-detection (default)
    //   "yes"  -> force present
    //   "no"   -> disable entirely
    char     battery_present[8];
    uint8_t  debounce_press_scans;    // Consecutive scans required to validate a press (default: 3)
    uint8_t  debounce_release_scans;  // Consecutive scans required to validate a release (default: 5)
} kb_power_config_t;

// -- Full config --
typedef struct {
    uint8_t             version;         // Schema version (for future migrations)
    uint8_t             profile_count;
    uint8_t             active_profile;
    kb_orientation_t    orientation;     // Global rotation (0/90/180/270 deg)
    kb_profile_t        profiles[CONFIG_MAX_PROFILES];
    uint8_t             macro_count;     // Global macros used (<= MACRO_COUNT)
    kb_macro_t          macros[MACRO_COUNT];
    kb_ble_config_t     ble;
    kb_display_config_t display;
    kb_encoder_config_t encoder;
    kb_led_extension_t  led_extension;
    kb_power_config_t   power;
} kb_config_t;

// -------------------------------------------------------------
//  PUBLIC FUNCTIONS
// -------------------------------------------------------------

// Initialize: load from NVS (or create a default config if absent)
esp_err_t config_store_init(void);

// Get a pointer to the config in memory (read-only)
const kb_config_t *config_store_get(void);

// Update the config from a JSON received via WebSerial/BLE
// json_str = null-terminated JSON string
esp_err_t config_store_update_from_json(const char *json_str);

// Save the current config to NVS
esp_err_t config_store_save(void);

// Set the active profile (data layer only): clamp to profile_count,
// update g_config.active_profile and persist to NVS. Does NOT touch the keymap
// or the screen - use keymap_set_active_profile() for the full switch.
// Writes the actually applied index (after clamp) into *applied if non-NULL.
esp_err_t config_store_set_active_profile(uint8_t idx, uint8_t *applied);

// Export the current config to JSON (into a buffer allocated by the caller)
// buffer must be large enough (use CONFIG_JSON_MAX_SIZE)
esp_err_t config_store_to_json(char *buffer, size_t buffer_size);

// Reset the config to zero (default values)
esp_err_t config_store_factory_reset(void);

#define CONFIG_JSON_MAX_SIZE  8192  // 8KB max for the config JSON
